package main

import (
  "../basics";
  //"../examples"
)

func main() {
  //basics.ShortHand()
  //basics.AsVars()
  //basics.Closure()
  //basics.BlankIdentifierExample()
  //basics.MemAddress()
  //basics.UseMemAddress()
  //basics.PointerExample()
  //basics.UseMemAddressAgain()
  //basics.ForLoop()
  //basics.WhileLoop()
  //basics.Cast()
  //basics.RuneCounter()
  //basics.SwitchFallthroughStatements()
  //basics.SwitchOnType(5)
  //basics.SwitchOnType("testing")
  //var t = basics.Contact{ "Hello!", "Ryan!" }
  //basics.SwitchOnType(t)
  //basics.IfInitializationStatements(false)
  //basics.GreetFull("Bill", "Burr")
  //fmt.Println(basics.ReturnExample("this is Ryan"))
  //fmt.Println(basics.ReturnAssigned("Ryan ", "Rules"))
  //fmt.Println(basics.ReturnAssigned("Ryan ", "Rules"))
  //fmt.Println(basics.ReturnMultiple("Ryan", "Dubs"))
  //fmt.Println(basics.FuncAverageVariadicParams(5.554, 76.766, 123.674, 22.32223))
  //basics.FuncAverageVariadicArgs()
  //basics.ExpressionExample()
  //basics.ClosureExpression()
  //basics.ClosureFunc()
  //basics.ClosureNotAnon()
  //basics.RunCallbacks()
  //examples.RunFilter()
  //basics.RunRecursiveFactorial()
  //basics.RunDefer(false)
  //basics.RunPassByValue()
  //basics.RunPassByReference()
  //basics.RunPassByReferenceMap()
  //basics.RunAnonymousSelfExecuting()
  //basics.SliceExample()
  //basics.RunInterfacesExample()
  //basics.RunConcurrency()
  basics.RunParallel()
  //fmt.Println(stringutil.MyName)
}
